### ISSUE TITLE
Ability to store reminders between combats

### ISSUE THREAD

**Issue by Shandyan** [schultzcole/FVTT-Turn-Alert#12]
For frequently used reminders, it'd be really useful to have a way to 'store' them, rather than needing to add them in manually each time.

**Comment by schultzcole** [comment]
Thank you for the request. Do you mean like a preset, that you could quickly add to the current combat?

**Comment by Shandyan** [comment]
User-generated presets would be great, with the ability to tweak them as they're applied.

For example,  I'd like to have one for a dragon's breath weapon, but won't know in advance how many rounds it will be. The advantage of the pre-set would be to have this already set to 'GM whisper', as the players shouldn't know this!

**Comment by schultzcole** [comment]
I think support for "presets" will be done via macros. Here's an example of a macro that will open the Turn Alert Configuration dialog with some preset values:

```js
const combatData = game.combat.data;
const alertData = {
    combatId: combatData._id, // add to the current combat
    createdRound: combatData.round, // set the round that the alert was created in
    round: 5, // set what round the alert will trigger on. This is the default, it can be changed in the config dialog
    roundAbsolute: false, // indicates that the "round" is relative to the "createdRound"
    turnId: combat.data.turns[combatData.turn]._id, // add to the current combatant's turn
    message: "Dragon Breath Weapon", // the message
    userId: game.userId, // indicates the user that created the alert
    recipientIds: [ game.userId ] // whisper the message to the current user only
};

new TurnAlertConfig(alertData).render(true);
```

To be frank, the addition of a fully blown preset system including UI and everything is more work than it's worth I think, especially when a macro can do just about the same thing. I do appreciate the suggestion though.

**Comment by Shandyan** [comment]
Fair enough! The macro looks super useful - I suggest that you add this macro to the documentation page for the module, so other people can see it?

**Comment by schultzcole** [comment]
Hi @Shandyan, I have created a wiki page where I'm keeping some example macros: https://github.com/schultzcole/FVTT-Turn-Alert/wiki/Example-Creation-Macros

I'll also be adding a selection of these macros to a compendium bundled with the module in a future update.
