### ISSUE TITLE
Persistent alerts between encounters

### ISSUE THREAD

**Issue by DieterKosken** [schultzcole/FVTT-Turn-Alert#21]
It would be great to be able to create default alerts to be persistent between encounters. This way, something that should happen in every encounter can be. 

Personally I was thinking running a lower shields macro or maybe toggle Oracle Curses.

**Comment by schultzcole** [comment]
Hi @DieterKosken. I'm sorry to say that I don't intend to add inter-combat persistent alerts, nor alerts that are automatically created when a new combat is created. Alerts are inherently tied to a specific `Combat` instance and I don't foresee that changing.

I would recommend for you to use a macro to quickly create an alert when a new combat is created.
