### ISSUE TITLE
Enable macros to create an alert

### ISSUE THREAD

**Issue by SalieriC** [schultzcole/FVTT-Turn-Alert#29]

**Comment by schultzcole** [comment]
Hello @SalieriC, I'm not sure I fully understand the question. You can already create an alert with a macro. I would encourage you to check out the [Turn Alert Wiki](https://github.com/schultzcole/FVTT-Turn-Alert/wiki) as well as the example macros compendium included with the module. Those should be a good starting point at least. Once you've looked through those, if you have a specific question ping me in the `#macro-polo` channel in the Foundry discord (`@cole#9640`).

If I've misinterpreted your question somehow, feel free to reopen the issue.
