### ISSUE TITLE
"Top of Round" alert does not run script macro

### ISSUE THREAD

**Issue by j-schoch** [schultzcole/FVTT-Turn-Alert#31]
Possibly related to https://github.com/schultzcole/FVTT-Turn-Alert/issues/30

Creating a "Top of Round" alert and assigning a Script Macro by name does not run the macro.  Chat macros work fine both in the popup interface and via macro name reference.

I've verified that the script macro works when executed manually, and works when assigned to a Player's turn rather than "Top of Round" section.

**Comment by schultzcole** [comment]
Thanks for the report! This should be resolved in 1.5.1
