### ISSUE TITLE
Non combat alerts?

### ISSUE THREAD

**Issue by JamzTheMan** [schultzcole/FVTT-Turn-Alert#35]
This may be out of your scope but it would be great if i could use your same module to track events outside of combat as well. 

Right now I use About Time for this but your approach is much cleaner using JSON.

Also, you could end up getting some poison or disease or effect in combat that persists after combat.

Now that there is a built in game world clock, would this be possible?

**Comment by schultzcole** [comment]
Hi Jamz, unfortunately this won't be feasible. Turn Alert has no understanding of time or the world clock, it is directly tied to combat rounds. Thank you for the suggestion though.
