### ISSUE TITLE
I can't see it in module settings anymore

### ISSUE THREAD

**Issue by KirikTheOrc** [schultzcole/FVTT-Turn-Alert#36]
I can't find it and it doesn't seem to work with the new update. I love this module, can you update it please? No rush

**Comment by schultzcole** [comment]
I can't seem to reproduce this issue. Can you tell me your core foundry version, turn alert version, and system version please?

**Comment by KirikTheOrc** [comment]
. . . man I was looking for turn alert instead of combat ready. I'm sorry I wasted your time.
