### ISSUE TITLE
"Add Alert" does not appear in combatant context menu 

### ISSUE THREAD

**Issue by Luisphigor** [schultzcole/FVTT-Turn-Alert#37]
149 / 5000
Hello,
This module would be very useful for my games as it effectively solves my needs to keep track of buffs/debuffs cooldowns during matches.

Unfortunately it doesn't seem to work. "Add Alert" does not appear in combatant context menu and nothing appens clicking on "+" buttons in combat alert window.

 I'm usign Fvtt v.0.8.6 and PF1 system 0.78.8
Probably due to FoundryVTT version compatibility issue? Is this module abandoned?

**Comment by schultzcole** [comment]
This issue should be fixed in Turn Alert 2.0.0
