### ISSUE TITLE
Developing question - Are you Planning to integrate this with AboutTime and similar module

### ISSUE THREAD

**Issue by p4535992** [schultzcole/FVTT-Turn-Alert#45]
Hi sorry to bother.

I wanted to know if are you Planning to integrate your module with time based module like the following:

- **About Time by tposney** - manage events and active effect time outs
- **Times Up by tposney** - Handles spell effects expiring when their time is up or after a certain number of rounds or turns
- **DAE by tposney** - With midi-qol, handles various additional expiration effects such as after 1 attack or when an enemy is attacked
- **Midi-QOL by tposney** - Handles a vast amount of automation relating to advantage and disadvantage

If this were not the case, I wanted to try to integrate it, would it be a pain for you to change your license to that of MIT?

**Comment by schultzcole** [comment]
No, I don't intend to integrate with other modules. Feel free to fork and make whatever changes you want, but I don't plan to change away from GPL license.

**Comment by schultzcole** [comment]
@p4535992 Hey I was just made aware of some of the licensing issues that could arise having to do with GPL and integrations with other software. I've opted to change turn alert to the MIT license as a result. Happy developing.

**Comment by p4535992** [comment]
A thousand thanks ! I too had recently encountered problems with the GPL license. I'll let you know if I can develop something that works ^^.
