### ISSUE TITLE
Include some macros both as API examples and also for ease of debugging.

### ISSUE THREAD

**Issue by schultzcole** [schultzcole/FVTT-Turn-Alert#8]
Some macros should be included to demonstrate how to use Turn Alert programmatically

It would also be nice if some debug macros could be added which would perhaps print out the active alerts on the current combat, etc.

**Comment by Nerull91** [comment]
Yes please, I want to tie in an alert to a macro when a player use a buff. I.e. Player use "raise shield" macro and it automatically create an alert that will trigger at the beginning of his next turn.

Thanks!
